name: architecture_template

sdkPath: .fvm/flutter_sdk

packages:
  - package/**

scripts:
  analyze:
    exec: dart analyze

  get:
    run: melos exec -c 1  -- "flutter pub get"

  clean:
    run: melos exec -c 1  -- "flutter clean"